### ISSUE TITLE
hey. can you help me in implementing this code in fairseq/transformer model? 

### ISSUE THREAD

**Issue by Rabailkamboh** [robflynnyh/hydra-linear-attention#1]

**Comment by robflynnyh** [comment]
Hi there! what is the issue that you are having? You should be able to drop this in in-place of attention, may want to keep a couple of normal attention layers tho.

**Comment by Rabailkamboh** [comment]
Hi Robert,

I am so Sorry as i missed your mail.
Actually i was trying to implement this hydra attention in NLP task for
Machine Translation. I am unable to do so. so i was reaching out to you to
get some help from you.

**Comment by robflynnyh** [comment]
what is the problem you are having with integrating it? Note you would only be able to use this in the encoder for MT as hydra won't work for the decoder as it would break causality

**Comment by Rabailkamboh** [comment]
i am having dimension errors. the code i tried is attached . the error i am
getting is also attached.in erro file the error is in the multihead
attention. dont get confused, actually i implemented hydra code in
multihead code file and removed the multihead actual calculation just to
adjust the hydra with the other necessary functions for machine translation
using fairseq library. so can you please help me with this one.

**Comment by robflynnyh** [comment]
hey I don't see an error file attached? This isn't really related to my code/this repo but if you put your code in a colab that reproduces the error you are getting when integrating it with your code, and link me I don't mind explaining whatever is wrong to you
